title: Synkyria
description: >
  © Panagiotis Kalomoirakis · Synkyria Project.
  All rights reserved. Selected works released under CC BY-NC-SA where stated.
theme: minima

header_pages:
  - index.md
  - how-to-read/index.md
  - library/index.md
  - about/index.md

defaults:
  - scope:
      path: ""
    values:
      layout: default

